org.slf4j.simpleLogger.defaultLogLevel=info
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss.SSS
org.slf4j.simpleLogger.log.org.apache.kafka=warn
org.slf4j.simpleLogger.log.org.apache.kafka.clients=warn
org.slf4j.simpleLogger.log.org.apache.kafka.clients.admin=warn
org.slf4j.simpleLogger.log.org.apache.kafka.clients.NetworkClient=warn
org.slf4j.simpleLogger.log.org.apache.kafka.clients.admin.internals.AdminMetadataManager=warn
org.slf4j.simpleLogger.log.org.apache.kafka.common.utils.AppInfoParser=warn
